project:
  type: book
  output-dir: docs

book:
  title: "Ecologie spatiale et régime alimentaire d'une espèce en danger critique d'extinction : apports pour la conservation du Vison d'Europe (*Mustela lutreola*)."
  author: 
  - name: Rémi Bodinier
    affiliation: GREGE, LBBE
    roles:
      - Writing
      - Doing the study
    email: 
      - rbodinier.grege@orange.fr
      - remi.bodinier@etu.univ-lyon1.fr

  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - methodo.qmd
    - resultats.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



