project:
  type: book
  output-dir: docs

book:
  title: "Ecologie spatiale et régime alimentaire d'une espèce en danger critique d'extinction : apports pour la conservation du Vison d'Europe (*Mustela lutreola*)."
  author: 
  - name: Rémi Bodinier
    affiliation: GREGE, LBBE
    email: 
      - rbodinier.grege@orange.fr
      - remi.bodinier@etu.univ-lyon1.fr

  date: today
  chapters:
    - index.qmd
    - part: j02intro.qmd
      chapters: 
        - j03intro_article.qmd
        - j04synt_biblio.qmd
    - part: j05methodo.qmd
      chapters: 
        - j06etude.qmd
        - j07met_deb_these.qmd
        - j08met_DV.qmd
        - j09met_habit.qmd
    - part: j10resultats.qmd
      chapters: 
        - j11DV.qmd
    - j12references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



