# Méthodologie
## Occupation de l'espace

Les domaines vitaux de tous les individus seront modélisés grâce à des nouvelles méthodes qui n’ont pas été utilisées jusqu’à présent pour le Vison d’Europe (Local Convex Hull (LoCoH), ponts browniens…), à partir des localisations quotidiennes de chaque individu. Les surfaces occupées ainsi estimées par chacune des modélisations seront comparées avec celles des modélisations les plus communément utilisées par les auteurs ayant travaillé sur l’espèce (MCP, Kernels). L’analyse devrait permettre de proposer la meilleure méthode à retenir pour la modélisation des domaines vitaux du Vison d’Europe, tout en tenant compte de la configuration bien différente des zones de marais et des vallées alluviales sinueuses. Les domaines vitaux seront ensuite analysés en fonction des caractéristiques des individus (sexe, classe d’âge, statut reproducteur…) par modèles mixtes en première intention car en effet ces modèles devront prendre en compte comme variable aléatoire entre autres la différence de temporalité entre les deux projets mais aussi d’autres facteurs temporaires (saisons…). Des tests subsidiaires de choix de modèle (Critère d’Information d’Akaike…) viendront compléter les analyses. La modélisation des surfaces exploitées sera également étudiée en fonction de la dispersion spatiale des localisations, afin de définir des zones plus ou moins utilisées au sein du domaine vital. Ces approches devraient donc permettre de mettre en évidence des « zones coeurs », c’est-à-dire des surfaces statistiquement plus utilisées que les zones fortement utilisées dans l’hypothèse d’une utilisation aléatoire de l’espace (Powell, 2000).

## Patrons de déplacements

Grâce aux suivis continus des individus dans les Landes de Gascogne, une étude de la trajectométrie pourra être faite afin de décrire des typologies de déplacements selon les différentes phases d’activité (chasse, déplacement entre gîte, …). Les modèles utilisés pour décrire ces phases d’activité devront prendre en compte certaines caractéristiques des individus (âge, sexe, statut reproducteur, …) et certaines caractéristiques spatiales relevées lors de la partie i.
La mobilité individuelle sera également étudiée d’une autre manière à partir des données qui correspondent aux localisations quotidiennes. En effet, Laundré et al. (1987) ont montré qu’utiliser des distances entre localisations relevées à un jour d’intervalle présentaient certains problèmes en tant qu’indicateur du trajet et des mouvements totaux d’un individu. De la trajectométrie ne peut donc pas être fait avec ces données et l’étude de la mobilité individuelle à partir des localisations quotidiennes sera donc menée en utilisant comme indicateur les distances entre deux localisations diurnes relevées à un jour d’intervalle. La modélisation de cet indicateur se fera en projetant chaque gîte sur l’axe médian du lit majeur du cours d’eau utilisé et en calculant la distance entre le gîte d’un jour et celui de la veille en suivant cet axe médian. Cette méthode est proposée pour venir se substituer aux distances euclidiennes, afin de mieux correspondre à la réalité du terrain et à la sinuosité des cours d’eau. Ensuite, les distances seront comparées sur des échelles temporelles différentes (jour, semaine, mois, saison…). Les distances seront aussi comparées en fonction du sexe, voire de l’âge et du statut reproducteur. De la même manière que pour l’étude de l’occupation de l’espace, les analyses seront des modèles prenant en compte les différentes variables d’influence, complétées par des analyses de choix de modèles. Ainsi, des périodes de plus ou moins forte mobilité seront définies et pourront être reliées à certains évènements (rut, reproduction, élevage des jeunes…). Afin de pouvoir relier les variations des distances parcourues et les évènements écologiques cités juste avant, il faudra prendre en compte les gîtes de reproduction dans cette étude. Ces périodes pourront être définies comme des périodes écologiques de l’espèce. En outre, la mobilité au sein des différentes parties des domaines vitaux sera également étudiée grâce aux résultats de la partie i.

## Utilisation de l'habitat

Il s’agira d’identifier les habitats utilisés et ceux sélectionnés par l’espèce pour installer ses gîtes diurnes grâce à la cartographie de l’occupation du sol réalisée. Deux approches complémentaires seront menées : 1) analyser les modalités d’utilisation des habitats en comparant les distributions des gîtes par habitat grâce à une analyse multivariée en composantes, 2) définir les sélections d’habitats en comparant en première intention les habitats des localisations à la disponibilité présente dans le domaine vital, c’est-à-dire une sélection du 3ème ordre (sensu Johnson, 1980). Les analyses seront faites grâce à une approche de type k-select (Calenge et al., 2005). L’utilisation et la sélection des habitats seront également analysées en fonction des caractéristiques des individus (sexe, classe d’âge, statut reproducteur…). De plus, une analyse temporelle pourra être menée en utilisant entre autres les périodes définies lors de l’analyse de la mobilité (partie ii.).
En outre, les compositions en habitats au sein des différentes surfaces décrites lors des analyses de l’occupation de l’espace (partie i.) mais aussi lors de la description des surfaces de chasse dans l’étude de la mobilité (partie ii.) seront également étudiées. Une analyse spatiale de l’utilisation et de la sélection des habitats sera ainsi menée.
Dans cette partie, les gîtes de repos et les gîtes de mises bas et d’élevage des jeunes ne seront pas approchés de la même façon, le choix du gîte de reproduction impliquant des critères différents (sécurité des jeunes, …). Une analyse descriptive de l’habitat utilisé pour installer le gîte de reproduction sera ainsi menée en parallèle, étant donné le faible nombre de gîtes de reproduction identifiés.

## Caractéristiques des gîtes

Il s’agira d’identifier les caractéristiques préférées dans l’établissement du gîte diurne. A partir des paramètres environnementaux relevés à une échelle fine sur chacun des gîtes identifiés par approche pédestres et cités dans la méthodologie, la préférence de certains de ces paramètres sera analysée selon les caractéristiques des individus (sexe, classe d’âge, statut reproducteur…). L’analyse devra également prendre en compte l’habitat dans lequel se situe le gîte diurne afin de relever de potentiels correspondances entre les deux variables. Une analyse multivariée de type canonique est pensée comme première approche (analyse procustéenne ou analyse de co-inertie). Enfin, des facteurs temporels (périodes définies lors de l’analyse de la mobilité partie ii.) et spatiaux (surfaces décrites dans l’étude de l’occupation de l’espace partie i.) devront être pris en compte pour expliquer les choix de certaines caractéristiques.
De même que dans l’étude de l’habitat, les gîtes de repos et les gîtes de mises bas et d’élevage des jeunes ne seront pas approchés de la même façon. Une analyse descriptive des caractéristiques préférées pour installer le gîte de reproduction sera ainsi menée en parallèle, pour les mêmes raisons que pour l’étude de l’habitat.

## Régime alimentaire

Pour finir, le régime alimentaire sera étudié grâce aux analyses de la composition de crottes récoltées sur les gîtes identifiés lors du radiopistage. Dans un premier temps, des indices de diversité ou de richesse (basé sur les indices de Shannon et de Simpson) seront calculés pour chacune des crottes et ces indices seront comparés au sein des habitats (partie iii.) et des surfaces (partie i.) dans lesquels les crottes sont trouvées. Le Vison d’Europe pouvant chasser entre deux gîtes diurnes, une attention particulière devra être porté à l’échelle à laquelle se feront les analyses. De plus, les études actuelles semblent montrer que cette espèce est généraliste, il faudra donc mettre en avant les habitats ou les surfaces dans lesquels les indices montrent une grande diversité d’espèces voire des taxons supérieurs. Ensuite, et sur le même principe que pour l’habitat, l’étude du régime alimentaire tentera de mettre en avant une sélection de certaines proies par les différents individus selon la ressource disponible dans le domaine vital. Il s’agira de comparer les disponibilités en proies relevées lors des inventaires aux proportions de proies retrouvées dans les fèces par une approche s’inspirant des méthodes analytiques de sélection des habitats (k-select, eigenanalysis, …). L’individu, le sexe et l’âge seront des variables à prendre en compte pour expliquer une potentielle sélection. Cette comparaison devra également prendre en compte la période (résultats de la partie ii.) puisque les proies du Vison d’Europe n’ont pas toutes la même écologie. Enfin, les crottes ayant été localisées, il est possible d’observer des différences de proies sélectionnées en fonction de la localisation au sein du domaine vital (dans ou hors zone coeur définies en partie i.).

## Risque de collisions routières


Pour cette analyse, des variables permettant d’estimer un risque de collision devront tout d’abord être identifiées. Ces variables prendront en compte les résultats des analyses précédentes mais pas seulement. En effet le premier type de variable se concentrera sur les composantes anthropiques (trafic routier sur le franchissement, distance au prochain franchissement le plus proche…). L’autre type de variables concernera des variables environnementales définies à partir des analyses précédentes, en particulier les résultats de l’analyse de l’utilisation de l’habitat partie iii (présence/absence d’habitats favorables dans un rayon défini par la mobilité journalière, présence/absence d’habitats favorables des deux côtés du franchissement et distance à ceux-ci…). Une analyse précise des collisions routières recensées lors des différents projets permettra d’associer à chacune des collisions des valeurs pour chacun des variables retenues. Une analyse multivariée en composante (analyse des correspondances multiples ou analyse mixte) permettra ensuite d’expliquer les facteurs principaux expliquant la mortalité par collision routière.
